### ISSUE TITLE
web site does not load

### ISSUE THREAD

**Issue by nameswastaken** [wish13yt/wishdog.link#3]
**Describe the bug**
website no work

**To Reproduce**

5.go to wishdog link

**Expected behavior**
it load

**Screenshots**
dont have any too lazy

**Desktop (please complete the following information):**
 - os chrome
 - browser chrome
 - version chrome

**Smartphone (please complete the following information):**
 - device chrome
 - os chrome
 - browser chrome
 - version 128

**Additional context**
fix your site

**Comment by wish13yt** [comment]
very well known issue, no clue how to fix :333333

**Comment by nameswastaken** [comment]
[Screen recording 2024-10-17 8.20.14 AM.webm](https://github.com/user-attachments/assets/b6dc2cbd-07e2-4699-9d0b-069d1a23b2c5)

**Comment by wish13yt** [comment]
fixed-ish, still insecure but actually loads now
